language: node_js
node_js:
  - 10
  - 12

sudo: false

before_install:
  - npm install -g codecov
  - npm install -g jest

script: jest --ci --coverage && codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
